# Generated by Django 4.1.6 on 2023-05-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portapp', '0002_delete_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUESTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(default=9)),
                ('q2', models.IntegerField(default=9)),
            ],
        ),
    ]
