# Generated by Django 4.1.6 on 2023-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q1',
        ),
        migrations.AddField(
            model_name='question',
            name='temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='q2',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
