# Generated by Django 4.1.6 on 2023-05-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_remove_question_q1_question_temp_alter_question_q2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q2',
            new_name='time',
        ),
    ]
