# Generated by Django 4.1.6 on 2023-10-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0006_alter_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='temp',
            field=models.CharField(max_length=900),
        ),
    ]
