# Generated by Django 4.1.6 on 2023-10-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0007_alter_question_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='temp',
            field=models.TextField(max_length=300),
        ),
    ]
