# Generated by Django 4.1.6 on 2023-10-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0008_alter_question_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='k',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='mos',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='n',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='p',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='ph',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='question',
            name='temp',
            field=models.FloatField(default=-1),
        ),
    ]
