# Generated by Django 4.1.6 on 2023-10-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0009_question_k_question_mos_question_n_question_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('time', models.IntegerField(default=9)),
            ],
        ),
    ]
