# Generated by Django 4.1.6 on 2023-10-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0010_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.CharField(default=9, max_length=100),
        ),
    ]
