# Generated by Django 4.1.6 on 2023-11-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0012_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='time',
            field=models.IntegerField(default=9),
        ),
    ]
