# Generated by Django 4.1.6 on 2023-11-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0013_door_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DOORFAIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.IntegerField(default=-1)),
                ('d2', models.IntegerField(default=-1)),
                ('time', models.IntegerField(default=9)),
            ],
        ),
    ]
