# Generated by Django 4.1.6 on 2023-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0014_active_doorfail'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='activatetime',
            field=models.CharField(default=9, max_length=100),
        ),
        migrations.AlterField(
            model_name='door',
            name='time',
            field=models.CharField(default=9, max_length=100),
        ),
        migrations.AlterField(
            model_name='doorfail',
            name='time',
            field=models.CharField(default=9, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.CharField(default=9, max_length=100),
        ),
    ]
