# Generated by Django 4.1.6 on 2023-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0015_active_activatetime_alter_door_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(default=9, max_length=100)),
                ('activatetime', models.CharField(default=9, max_length=100)),
            ],
        ),
    ]
