# Generated by Django 4.1.6 on 2023-11-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0016_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='d2',
        ),
        migrations.RemoveField(
            model_name='doorfail',
            name='d2',
        ),
    ]
