# Generated by Django 4.1.6 on 2023-11-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0018_remove_door_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='time',
            field=models.CharField(default=9, max_length=100),
        ),
    ]
