# Generated by Django 4.1.6 on 2023-11-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0020_door_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='day',
        ),
    ]
